---
# yamllint disable rule:line-length

variables:
  ALLOW_FAILURE_PHPCPD: "true"  # Problème de code dupliqué.
  ALLOW_FAILURE_PHPMD: "true"  # Problème de code dupliqué.
  ALLOW_FAILURE_VALIDATE: "true"  # Manque une table enrol_select.

  ENABLE_BEHAT: "false"  # Non implémenté.

  MOODLE_EXTRA_PLUGINS: >
    https://github.com/apsolu/block_apsolu_course.git
    https://github.com/apsolu/block_apsolu_dashboard.git
    https://github.com/apsolu/local_apsolu.git
    https://github.com/apsolu/theme_apsolu.git

include:
  - local: "/.gitlab/moodle401.yml"
